#!/usr/bin/env bash
### AUTOMATIC WORDPRESS SETUP BY WEBSTACK.UP
#@-- source /usr/local/turbolab.it/webstackup/script/base.sh
#@-- WEBROOT_DIR=
#@-- EXPECTED_USER=
#@-- 
#@-- source ${WEBSTACKUP_AUTOGENERATED_DIR}my-app.mysql.conf
#@-- MYSQL_DB_NAME=
#@-- MYSQL_USER=
#@-- MYSQL_HOST=
#@-- MYSQL_PASSWORD=
#@-- 
#@-- SITE_URL=
#@-- WORDPRESS_SITE_NAME="🚀 WordPress"
#@-- WORDPRESS_LOCALE=it_IT
#@-- 
#@-- WORDPRESS_ADMIN_USERNAME=
#@-- WORDPRESS_ADMIN_EMAIL=
#@-- 
#@-- WORDPRESS_MULTISITE_MODE=<null> | subfolders | subdomains
#@-- WORDPRESS_ADMIN_NEW_SLUG=
#@-- 
#@-- source ${WEBSTACKUP_SCRIPT_DIR}frameworks/wordpress/install.sh

if ! [ $(id -u) = 0 ]; then
  echo -e "\e[1;41m This script must run as ROOT \e[0m"
  return 1
fi

WPINST_WEBROOT_DIR=${WEBROOT_DIR%*/}/

if [ ! -f /usr/local/bin/wp-cli ]; then

  printTitle "Installing wp-cli..."
  curl -o /usr/local/bin/wp-cli  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  chmod u=rwx,go=rx /usr/local/bin/wp-cli
fi

if [ -z "$WP_EXE" ]; then

  WPINST_WP_EXE="sudo -u $EXPECTED_USER -H /usr/local/bin/wp-cli --path=${WPINST_WEBROOT_DIR}"
  
else

  WPINST_WP_EXE=${WP_EXE}
fi

printTitle "Downloading WordPress..."
## https://developer.wordpress.org/cli/commands/core/download/
$WPINST_WP_EXE core download \
  --locale="${WORDPRESS_LOCALE}" \
  --skip-content

printTitle "Checking WordPress version..."
$WPINST_WP_EXE core version

printTitle "Creating wp-config.php..."
## https://developer.wordpress.org/cli/commands/config/create/
$WPINST_WP_EXE config create \
  --dbname="${MYSQL_DB_NAME}" \
  --dbuser="${MYSQL_USER}" \
  --dbhost="${MYSQL_HOST}" \
  --dbpass="${MYSQL_PASSWORD}" \
  --locale="${WORDPRESS_LOCALE}"

printTitle "Installing WordPress..."
WPINST_FIRST_ADMIN_PASSWORD=$(head /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 19)
WPINST_SITE_DOMAIN=$(echo $SITE_URL | sed 's/https\?:\/\///')
WPINST_SITE_DOMAIN=${WPINST_SITE_DOMAIN%*/}


if [ ! -z $WORDPRESS_MULTISITE_MODE  ]; then

  printMessage "Installing in MULTISITE mode"
  if [ $WORDPRESS_MULTISITE_MODE == "subdomains" ] || [ $WORDPRESS_MULTISITE_MODE == "subdomain" ]; then
    local $WPINST_WORDPRESS_MULTISITE_MODE_ARGUMENT=--subdomains
  fi
  
  ## https://developer.wordpress.org/cli/commands/core/multisite-install/
  $WPINST_WP_EXE core multisite-install \
    --url="${WPINST_SITE_DOMAIN}" \
	$WPINST_WORDPRESS_MULTISITE_MODE_ARGUMENT \
    --title="${WORDPRESS_SITE_NAME}" \
    --admin_user="${WORDPRESS_ADMIN_USERNAME}" \
    --admin_email="${WORDPRESS_ADMIN_EMAIL}" \
    --admin_password="${WPINST_FIRST_ADMIN_PASSWORD}" \
    --skip-email
	
else

  printMessage "Installing in SINGLE-SITE mode"

  ## https://developer.wordpress.org/cli/commands/core/install/
  $WPINST_WP_EXE core install \
    --url="${WPINST_SITE_DOMAIN}" \
    --title="${WORDPRESS_SITE_NAME}" \
    --admin_user="${WORDPRESS_ADMIN_USERNAME}" \
    --admin_email="${WORDPRESS_ADMIN_EMAIL}" \
    --admin_password="${WPINST_FIRST_ADMIN_PASSWORD}" \
    --skip-email
fi


printTitle "Installing WordPress plugin..."
## https://developer.wordpress.org/cli/commands/plugin/install/
# https://wordpress.org/plugins/wps-hide-login/
$WPINST_WP_EXE plugin install \
  wps-hide-login \
  --activate-network --activate
  
printTitle "Enable plugin auto-update..."
$WPINST_WP_EXE plugin auto-updates enable \
  --all

printTitle "Setting some options..."
## https://wordpress.org/support/topic/change-admin-url-through-wp-cli/
$WPINST_WP_EXE option update \
  whl_page "${WORDPRESS_ADMIN_NEW_SLUG}" \
  --skip-plugins --skip-themes

printTitle "Set the permissions"
chown webstackup:www-data ${WPINST_WEBROOT_DIR} -R
chmod u=rwx,g=rwX,o=rX ${WPINST_WEBROOT_DIR} -R
chmod u=rw,g=r,o= ${WPINST_WEBROOT_DIR}wp-config.php

printMessage "Your admin password is: $WPINST_FIRST_ADMIN_PASSWORD"
