#!/usr/bin/env bash
### AUTOMATIC HTTP BASIC AUTH GENERATOR BY WEBSTACKUP
# https://github.com/TurboLabIt/webstackup/tree/master/script/account/generate-http-basic-auth.sh
#
# sudo apt install curl -y && curl -s https://raw.githubusercontent.com/TurboLabIt/webstackup/master/script/account/generate-http-basic-auth.sh | sudo bash

## bash-fx
if [ -f "/usr/local/turbolab.it/bash-fx/bash-fx.sh" ]; then
  source "/usr/local/turbolab.it/bash-fx/bash-fx.sh"
else
  source <(curl -s https://raw.githubusercontent.com/TurboLabIt/bash-fx/main/bash-fx.sh)
fi
## bash-fx is ready

fxHeader "🛅 HTTP Basic Auth Generator"
rootCheck

fxTitle "Installing additional utilities..."
apt install openssl -y

fxTitle "📂 Creating the autogenerated folder..."
BASICAUTH_AUTOGEN_DIR=/usr/local/turbolab.it/webstackup/autogenerated/
mkdir -p ${BASICAUTH_AUTOGEN_DIR}

fxTitle "Generating the httpauth default file..."
HTTPAUTH_FULLFILE=${BASICAUTH_AUTOGEN_DIR}httpauth_welcome

echo -n 'wel:' > "$HTTPAUTH_FULLFILE"
openssl passwd -apr1 'come' >> "$HTTPAUTH_FULLFILE"
echo '' >> "$HTTPAUTH_FULLFILE"

echo -n 'ben:' >> "$HTTPAUTH_FULLFILE"
openssl passwd -apr1 'venuto' >> "$HTTPAUTH_FULLFILE"
echo '' >> "$HTTPAUTH_FULLFILE"

fxMessage "Ready-to-use HTTP credentials are:
User: wel | Pass: come
User: ben | Pass: venuto"

fxEndFooter
