#!/usr/bin/env bash
### AUTOMATIC MYSQL MAINTENANCE BY WEBSTACK.UP
#

## THIS SCRIPT WAS MADE IN A RUSH AND NEEDS SOME LOVE

source /etc/turbolab.it/mysql.conf

mysql -u"${MYSQL_USER}" -p "${MYSQL_PASSWORD}" -h "${MYSQL_HOST}" -e 'PURGE BINARY LOGS BEFORE DATE(NOW() - INTERVAL 1 DAY) + INTERVAL 0 SECOND;'
