#!/usr/bin/env bash
### GUIDED MySQL USER CREATION BY WEBSTACK.UP
# https://github.com/TurboLabIt/webstackup/tree/master/script/mysql/new.sh
#

echo ""
echo -e "\e[1;46m ============================ \e[0m"
echo -e "\e[1;46m 🗄️ MYSQL NEW DATABASE ACCESS \e[0m"
echo -e "\e[1;46m ============================ \e[0m"

if ! [ $(id -u) = 0 ]; then
  echo -e "\e[1;41m This script must run as ROOT \e[0m"
  exit
fi

source "/usr/local/turbolab.it/webstackup/script/base.sh"

MYSQL_CREDENTIALS_FILE=/etc/turbolab.it/mysql.conf
if [ ! -f ${MYSQL_CREDENTIALS_FILE} ]; then
  catastrophicError "Credentials file ${MYSQL_CREDENTIALS_FILE} not found!"
  exit;
fi


NEW_MYSQL_USER=$1
NEW_MYSQL_PASSWORD=$2
NEW_MYSQL_DB_NAME=$3

if [ -z $NEW_MYSQL_USER ] || [ -z $NEW_MYSQL_PASSWORD ] || [ -z $NEW_MYSQL_DB_NAME ]; then
  NEW_MYSQL_USER=
  NEW_MYSQL_PASSWORD=
  NEW_MYSQL_DB_NAME=
fi


printTitle "🧔 Username"
while [ -z "$NEW_MYSQL_USER" ]
do
  read -p "🤖 Provide the username: " NEW_MYSQL_USER  < /dev/tty
done


printTitle "🔑 Password"
while [ -z "$NEW_MYSQL_PASSWORD" ]
do
  read -p "🤖 Provide the password (leave blank for autogeneration): " NEW_MYSQL_PASSWORD  < /dev/tty
  
  if [ -z "$NEW_MYSQL_PASSWORD" ]; then
    NEW_MYSQL_PASSWORD="$(head /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 19)"
  fi
  
done


printTitle "🧺 DB name"
while [ -z "$NEW_MYSQL_DB_NAME" ]
do
  read -p "🤖 Provide the name of the database to create: " NEW_MYSQL_DB_NAME  < /dev/tty
done


if [ -z "$(command -v git)" ]; then

  printTitle "📦 Installing prerequisites..."
  apt update && apt install mysql-client -y
  
fi


printMessage "🧔 Creating user..."  
wsuMysql -e "CREATE USER '$NEW_MYSQL_USER'@'%' IDENTIFIED BY '$NEW_MYSQL_PASSWORD';"

printMessage "🧺 Creating database..."
wsuMysql -e "CREATE DATABASE \`$NEW_MYSQL_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"

printMessage "🔑 Granting privileges..."
wsuMysql -e "GRANT ALL PRIVILEGES ON \`${NEW_MYSQL_DB_NAME//_/\\_}%\`.* TO '$NEW_MYSQL_USER'@'%';"
wsuMysql -e "FLUSH PRIVILEGES;"

MYSQL_NEW_CREDENTIALS_STORE_FILE=${WEBSTACKUP_AUTOGENERATED_DIR}${NEW_MYSQL_USER}.mysql.conf
wsuMysqlStoreCredentials "$NEW_MYSQL_USER" "$NEW_MYSQL_PASSWORD" "$MYSQL_HOST" "$MYSQL_NEW_CREDENTIALS_STORE_FILE" "$NEW_MYSQL_DB_NAME"

fxEndFooter
