## 🪄 Based on https://github.com/TurboLabIt/webstackup/blob/master/script/php-pages/symfony-bundle-builder/config/services.yaml
services:
    MyVendorName\MyPackageNameBundle\Service\MyService:
      autowire: true
      public: true

