#!/usr/bin/env bash
### THIRD-PARTY APT REPOS PINNED BY WEBSTACKUP
## The vendor's packages always win over Ubuntu's, and Ubuntu's builds of the same software can never be installed,
## not even when the repo is broken: see fxAptPinRepo in bash-fx for how and why.
##
## Every installer runs "wsuAptPin <name>" right after "fxAptUpdate 0": the pin lists the packages the repo really
## ships, so its index must be there. setup.sh runs wsuAptPinRefresh at each webstackup update (zzupdate): every repo
## below which is configured on the system gets its pin (re)generated with the current rules, pinned before or not.
##
## name | repo URI as the installer configures it, glob(7) allowed | Ubuntu-only packages of the same product, which
## are also the whole list when the repo has no index (fxAptPinRepo $3)
WSU_APT_PIN_REPOS="
mysql|http*://repo.mysql.com/apt/ubuntu/|mysql-* default-mysql-* default-libmysqlclient-dev libmysqlclient-dev
nginx|http*://nginx.org/packages/*|nginx* libnginx-mod-*
redis|http*://packages.redis.io/deb/|redis*
varnish|http*://packagecloud.io/varnishcache/varnish*/ubuntu/|varnish* libvarnishapi*
elasticsearch|http*://artifacts.elastic.co/packages/*/apt/|
opensearch|http*://artifacts.opensearch.org/releases/bundle/opensearch/*/apt/|
syncthing|http*://apt.syncthing.net/|syncthing syncthing-discosrv syncthing-relaysrv
"


function wsuAptPin()
{
  local WSU_APT_PIN_NAME WSU_APT_PIN_URI WSU_APT_PIN_EXTRA
  IFS='|' read -r WSU_APT_PIN_NAME WSU_APT_PIN_URI WSU_APT_PIN_EXTRA < <(
    echo "$WSU_APT_PIN_REPOS" | awk -F'|' -v NAME="$1" '$1 == NAME'
  )

  if [ -z "$1" ] || [ -z "$WSU_APT_PIN_URI" ]; then

    fxCatastrophicError "wsuAptPin: unknown repo ##${1}##" 0
    return 1
  fi

  fxAptPinRepo "$WSU_APT_PIN_NAME" "$WSU_APT_PIN_URI" "$WSU_APT_PIN_EXTRA"
  local WSU_APT_PIN_RESULT=$?

  ## written by the syncthing installer before this: superseded by 99syncthing
  if [ "$WSU_APT_PIN_NAME" = "syncthing" ] && [ -f /etc/apt/preferences.d/99syncthing ] && [ -f /etc/apt/preferences.d/syncthing.pref ]; then
    sudo rm -f /etc/apt/preferences.d/syncthing.pref
  fi

  return $WSU_APT_PIN_RESULT
}


## (re)pin every repo of the list which is configured on this system: run by setup.sh at each webstackup update
function wsuAptPinRefresh()
{
  fxTitle "📌 Pinning the third-party APT repos configured on this system..."

  if [ -z "$(command -v fxAptPinRepo)" ]; then

    fxWarning "bash-fx is stale (no fxAptPinRepo): update it, then run the webstackup setup again"
    return 1
  fi

  local WSU_APT_PIN_LINES WSU_APT_PIN_LINE WSU_APT_PIN_NAME WSU_APT_PIN_URI WSU_APT_PIN_FOUND=0
  mapfile -t WSU_APT_PIN_LINES <<< "$WSU_APT_PIN_REPOS"

  for WSU_APT_PIN_LINE in "${WSU_APT_PIN_LINES[@]}"; do

    IFS='|' read -r WSU_APT_PIN_NAME WSU_APT_PIN_URI _ <<< "$WSU_APT_PIN_LINE"
    if [ -z "$WSU_APT_PIN_NAME" ]; then
      continue
    fi

    if fxAptRepoIsConfigured "$WSU_APT_PIN_URI"; then

      WSU_APT_PIN_FOUND=1
      wsuAptPin "$WSU_APT_PIN_NAME"

    elif grep -qs "^## Generated by bash-fx fxAptPinRepo" "/etc/apt/preferences.d/99${WSU_APT_PIN_NAME}"; then

      fxWarning "The ${WSU_APT_PIN_NAME} repo is gone, but /etc/apt/preferences.d/99${WSU_APT_PIN_NAME} still blocks Ubuntu's packages: delete it if that's not intended"
    fi
  done

  if [ "$WSU_APT_PIN_FOUND" = "0" ]; then
    fxInfo "🐇 None configured"
  fi
}
