#!/usr/bin/env bash
## Run Symfony migrations by WEBSTACKUP
# Install instruction: https://github.com/TurboLabIt/webstackup/blob/master/script/frameworks/symfony/migrate-sh

source $(dirname $(readlink -f $0))/script_begin.sh
source "${WEBSTACKUP_SCRIPT_DIR}frameworks/symfony/migrate.sh"
source "${SCRIPT_DIR}/script_end.sh"
