#!/bin/bash

## kill the whole script on Ctrl+C
trap "exit" INT

##
if [ -z "$TIME_START" ]; then
  TIME_START="$(date +%s)"
fi

#### Webstackup directory
WEBSTACKUP_INSTALL_DIR_PARENT=/usr/local/turbolab.it/
WEBSTACKUP_INSTALL_DIR=${WEBSTACKUP_INSTALL_DIR_PARENT}webstackup/
WEBSTACKUP_AUTOGENERATED_DIR=${WEBSTACKUP_INSTALL_DIR}autogenerated/
WEBSTACKUP_CONFIG_DIR=${WEBSTACKUP_INSTALL_DIR}config/
WEBSTACKUP_SCRIPT_DIR=${WEBSTACKUP_INSTALL_DIR}script/

function wsuMkAutogenDir()
{
  fxTitle "📂 Creating the autogenerated folder..."
  mkdir -p "${WEBSTACKUP_AUTOGENERATED_DIR}"
}


#### Calling script paths (it works only when it's called as `source base.sh`)
## Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT_FULLPATH=$(readlink -f "$0")

## Absolute path this script is in, thus /home/user/bin
SCRIPT_DIR=$(dirname "$SCRIPT_FULLPATH")/

##
INITIAL_DIR=$(pwd)
PROJECT_DIR=$(readlink -m "${SCRIPT_DIR}..")/
WEBROOT_DIR=${PROJECT_DIR}public/
DB_DUMP_DIR=${PROJECT_DIR}backup/db-dumps/

function wsuMkDbDumpDir()
{
  fxTitle "📂 Creating the DB_DUMP_DIR folder..."
  mkdir -p "${DB_DUMP_DIR}"
  sudo chown --reference="${DB_DUMP_DIR}.." "${DB_DUMP_DIR}"
  sudo chmod --reference="${DB_DUMP_DIR}.." "${DB_DUMP_DIR}"
}

##
source "/usr/local/turbolab.it/bash-fx/bash-fx.sh"
source "${WEBSTACKUP_SCRIPT_DIR}php/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}mysql/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}frameworks/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}notify/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}deprecated-retrocompat.sh"

HOSTNAME="$(hostname)"
CURRENT_LANG=$(grep '^LANG=' /etc/default/locale | cut -d= -f2 | tr -d '"')
INSTALLED_RAM=$(awk '/MemFree/ { printf "%.3f \n", $2/1024/1024 }' /proc/meminfo)
INSTALLED_RAM="${INSTALLED_RAM//.}"


function wsuMirrorSsh()
{
  local DIRECTION="${1}"
  local REMOTE_USER="${2}"
  local REMOTE_HOST="${3}"
  local REMOTE_PATH="${4}"
  local LOCAL_PATH="${5}"
  local DELAY_OPT="${6}"

  fxTitle "🪞 Mirroring!"
  if [ -z "$(command -v rclone)" ]; then

    fxWarning "rclone is not installed. Installing it now..."
    curl https://rclone.org/install.sh | sudo bash
  fi

  if [ -z "${REMOTE_USER}" ]; then
    fxCatastrophicError "Please provide the remote username"
  fi

  if [ -z "${REMOTE_HOST}" ]; then
    fxCatastrophicError "Please provide the remote hostname"
  fi

  if [ -z "${REMOTE_PATH}" ]; then
    fxCatastrophicError "Please provide the remote path"
  fi

  if [ -z "${LOCAL_PATH}" ]; then
    fxCatastrophicError "Please provide the local path"
  fi

  local SFTP_PATH=":sftp:${REMOTE_PATH}"
  local SRC DST LABEL_FROM LABEL_TO

  if [ "${DIRECTION}" = "from" ]; then

    SRC="${SFTP_PATH}"
    DST="${LOCAL_PATH}"
    LABEL_FROM="${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
    LABEL_TO="${LOCAL_PATH}"

  elif [ "${DIRECTION}" = "to" ]; then

    SRC="${LOCAL_PATH}"
    DST="${SFTP_PATH}"
    LABEL_FROM="${LOCAL_PATH}"
    LABEL_TO="${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"

  else

    fxCatastrophicError "Direction must be 'from' or 'to'"
  fi

  local -a RCLONE_FULL_COMMAND=(
    rclone sync
    --sftp-ssh "ssh ${REMOTE_USER}@${REMOTE_HOST}"
    --sftp-disable-hashcheck
    --create-empty-src-dirs
    --links
    --transfers 32 --checkers 64
    --retries 5 --low-level-retries 10
    --log-level ERROR
    --progress
    --delete-excluded
    --exclude '*.log' --exclude '*.log.[0-9]*'
    --filter='+ var/log/.gitignore' --filter='- var/log/**'
    --filter='+ var/logs/.gitignore' --filter='- var/logs/**'
    --filter='+ var/cache/.gitignore' --filter='- var/cache/**'
    --filter='+ var/tmp/.gitignore' --filter='- var/tmp/**'
    --filter='+ var/session/.gitignore' --filter='- var/session/**'
    --filter='+ var/sessions/.gitignore' --filter='- var/sessions/**'
    "${SRC}"
    "${DST}"
  )

  echo "From: ${LABEL_FROM}"
  echo "To:   ${LABEL_TO}"
  echo ""

  if [ "${DELAY_OPT}" != "no-delay" ]; then

    echo "${RCLONE_FULL_COMMAND[@]}"
    echo ""
    fxCountdown
  fi

  "${RCLONE_FULL_COMMAND[@]}"
}


function wsuMirrorFromSsh()
{
  wsuMirrorSsh "from" "$1" "$2" "$3" "$4" "$5"
}


function wsuMirrorToSsh()
{
  wsuMirrorSsh "to" "$1" "$2" "$3" "$4" "$5"
}


## dialog default
HEIGHT=25
WIDTH=75
CHOICE_HEIGHT=30
BACKTITLE="WEBSTACKUP - TurboLab.it"
MENU="Choose one task:"
