#!/bin/bash

## kill the whole script on Ctrl+C
trap "exit" INT

##
if [ -z "$TIME_START" ]; then
  TIME_START="$(date +%s)"
fi

#### Webstackup directory
WEBSTACKUP_INSTALL_DIR_PARENT=/usr/local/turbolab.it/
WEBSTACKUP_INSTALL_DIR=${WEBSTACKUP_INSTALL_DIR_PARENT}webstackup/
WEBSTACKUP_AUTOGENERATED_DIR=${WEBSTACKUP_INSTALL_DIR}autogenerated/
WEBSTACKUP_CONFIG_DIR=${WEBSTACKUP_INSTALL_DIR}config/
WEBSTACKUP_SCRIPT_DIR=${WEBSTACKUP_INSTALL_DIR}script/

function wsuMkAutogenDir()
{
  fxTitle "📂 Creating the autogenerated folder..."
  mkdir -p "${WEBSTACKUP_AUTOGENERATED_DIR}"
}


#### Calling script paths (it works only when it's called as `source base.sh`)
## Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT_FULLPATH=$(readlink -f "$0")

## Absolute path this script is in, thus /home/user/bin
SCRIPT_DIR=$(dirname "$SCRIPT_FULLPATH")/

##
INITIAL_DIR=$(pwd)
PROJECT_DIR=$(readlink -m "${SCRIPT_DIR}..")/
WEBROOT_DIR=${PROJECT_DIR}public/
DB_DUMP_DIR=${PROJECT_DIR}backup/db-dumps/

function wsuMkDbDumpDir()
{
  fxTitle "📂 Creating the DB_DUMP_DIR folder..."
  mkdir -p "${DB_DUMP_DIR}"
  sudo chown --reference="${DB_DUMP_DIR}.." "${DB_DUMP_DIR}"
  sudo chmod --reference="${DB_DUMP_DIR}.." "${DB_DUMP_DIR}"
}

##
source "/usr/local/turbolab.it/bash-fx/bash-fx.sh"
source "${WEBSTACKUP_SCRIPT_DIR}php/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}mysql/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}frameworks/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}notify/commands.sh"
source "${WEBSTACKUP_SCRIPT_DIR}deprecated-retrocompat.sh"

HOSTNAME="$(hostname)"
CURRENT_LANG=$(grep '^LANG=' /etc/default/locale | cut -d= -f2 | tr -d '"')
INSTALLED_RAM=$(awk '/MemFree/ { printf "%.3f \n", $2/1024/1024 }' /proc/meminfo)
INSTALLED_RAM="${INSTALLED_RAM//.}"

WSUMIRROR_OPTIONS=(--archive --compress --delete --partial --info=progress2 --exclude '*.log' --exclude '*.log.[0-9]*')
function wsuMirror()
{
  if [ -z "${1}" ]; then
    fxCatastrophicError "Please provide the source!"
  fi

  if [ -z "${2}" ]; then
    fxCatastrophicError "Please provide the target!"
  fi

  fxTitle "Mirroring!"
  echo "From: ${1}"
  echo "To:   ${2}"

  if [ "${3}" != "no-delay" ]; then
    fxCountdown
  fi

  rsync "${WSUMIRROR_OPTIONS[@]}" "$1" "$2"
}


## dialog default
HEIGHT=25
WIDTH=75
CHOICE_HEIGHT=30
BACKTITLE="WEBSTACKUP - TurboLab.it"
MENU="Choose one task:"
