#!/bin/bash

echo ""
echo -e "\e[1;46m ==================== \e[0m"
echo -e "\e[1;46m 📚 DEPLOY NEW SERVER \e[0m"
echo -e "\e[1;46m ==================== \e[0m"

if ! [ $(id -u) = 0 ]; then
  echo -e "\e[1;41m This script must run as ROOT \e[0m"
  exit
fi

source "$(dirname "$(readlink -f "$0")")/base.sh"

printMessage "Loading default config..."
source ${WEBSTACKUP_INSTALL_DIR}webstackup.default.conf

## Default config error!
if [[ $WEBSTACKUP_ENABLED != 1 ]]; then
  catastrophicError "Default config file not available or script disabled"
fi


## Config file from CLI
CONFIGFILE_FULLPATH=$1
if [ ! -z "$CONFIGFILE_FULLPATH" ] && [ ! -f "$CONFIGFILE_FULLPATH" ]; then

  catastrophicError "Config file not found!
Please check if the following file exists and is accessible:
  
$CONFIGFILE_FULLPATH"

fi


## Config file from CLI OK
if [ ! -z "$CONFIGFILE_FULLPATH" ]; then
  
  printTitle "Importing custom options"
  source "$CONFIGFILE_FULLPATH"
  
  printMessage "Custom options imported from $CONFIGFILE_FULLPATH"
  
else

  CONFIGFILE_NAME=webstackup.conf
  CONFIGFILE_FULLPATH_ETC=/etc/turbolab.it/$CONFIGFILE_NAME

  for CONFIGFILE_FULLPATH in "$CONFIGFILE_FULLPATH_ETC"
  do
    if [ -f "$CONFIGFILE_FULLPATH" ]; then
    
      source "$CONFIGFILE_FULLPATH"
    fi
  done
fi


printTitle "Installing WEBSTACK.UP..."
if [ $INSTALL_WEBSTACKUP = 1 ]; then

  printMessage "Installing dependencies..."
  apt update -qq
  apt install git software-properties-common gnupg2 dialog htop screen openssl zip unzip -y -qq
  
  printMessage "Creating a folder for the autogenerated files..."
  mkdir -p "${WEBSTACKUP_AUTOGENERATED_DIR}"
  >"${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
  
  printMessage "Creating a new user account (the deployer)..."
  id -u webstackup &>/dev/null || useradd -G www-data webstackup --shell=/bin/false --create-home
  printMessage $(cat /etc/passwd | grep webstackup)
  
  printMessage "Generating an SSH key..."
  DEPLOYER_SSH_DIR=/home/webstackup/.ssh/
  mkdir -p "${DEPLOYER_SSH_DIR}"
  ssh-keyscan -t rsa github.com > "${DEPLOYER_SSH_DIR}known_hosts"
  touch "${DEPLOYER_SSH_DIR}config"
  chown webstackup:webstackup "${DEPLOYER_SSH_DIR}" -R
  
  chmod u=rwX,go= "${DEPLOYER_SSH_DIR}" -R
  sudo -u webstackup -H ssh-keygen -t rsa -f "${DEPLOYER_SSH_DIR}id_rsa" -N ''
  
  chmod u=rX,go= "${DEPLOYER_SSH_DIR}" -R
  chmod u=rw,go= "${DEPLOYER_SSH_DIR}known_hosts"
  
  sudo -u webstackup -H git config --global user.name "webstack.up"
  sudo -u webstackup -H git config --global user.email "info@webstack.up"
  
  printMessage "Keep SSH alive..."
  cp "${WEBSTACKUP_INSTALL_DIR}config/ssh/keepalive.conf" /etc/ssh/sshd_config.d/
  
  printMessage "Updating MOTD"
  source "${WEBSTACKUP_SCRIPT_DIR}filesystem/motd.sh"

else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing cron..."
if [ $INSTALL_CRON = 1 ]; then
  apt install cron -y -qq
fi


printTitle "Set the timezone..."
if [ ! -z "$INSTALL_TIMEZONE" ]; then 

  timedatectl set-timezone $INSTALL_TIMEZONE
  service syslog restart
  service cron restart
fi


printTitle "Installing NGINX..."
if [ $INSTALL_NGINX = 1 ]; then
  
  printMessage "Removing previous version (if any)"
  apt purge --auto-remove nginx* -y -qq
  
  source ${WEBSTACKUP_SCRIPT_DIR}nginx/install.sh

  ## Create self-signed, bogus certificates (so that we can disable plain-HTTP completely)
  source "${WEBSTACKUP_SCRIPT_DIR}https/self-sign-generate.sh" localhost
  
  printMessage "Generating dhparam..."
  openssl dhparam -out "${WEBSTACKUP_AUTOGENERATED_DIR}dhparam.pem" 2048 > /dev/null

  printMessage "Generating the httpauth default file..."
  HTTPAUTH_FULLFILE=${WEBSTACKUP_AUTOGENERATED_DIR}httpauth_welcome

  echo -n 'wel:' > "$HTTPAUTH_FULLFILE"
  openssl passwd -apr1 'come' >> "$HTTPAUTH_FULLFILE"
  echo '' >> "$HTTPAUTH_FULLFILE"

  echo -n 'ben:' >> "$HTTPAUTH_FULLFILE"
  openssl passwd -apr1 'venuto' >> "$HTTPAUTH_FULLFILE"
  echo '' >> "$HTTPAUTH_FULLFILE"

  printMessage "Ready-to-use HTTP Auth will be:
User: wel | Pass: come
User: ben | Pass: venuto"
  
  printMessage "Moving the original config outta way..."
  mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d_default_original_backup.conf

  printMessage "Upgrade all to HTTPS..."
  ln -s "${WEBSTACKUP_INSTALL_DIR}config/nginx/00_global_https_upgrade_all.conf" /etc/nginx/conf.d/

  printMessage "Disable the default website..."
  ln -s "${WEBSTACKUP_INSTALL_DIR}config/nginx/05_global_default_vhost_disable.conf" /etc/nginx/conf.d/
  
  printMessage "Enabling the http-block level functionality"
  ln -s "${WEBSTACKUP_INSTALL_DIR}config/nginx/02_global_http_level.conf" /etc/nginx/conf.d/
  
  service nginx restart
  systemctl --no-pager status nginx
  nginx -t
  
  WWW_DATA_HOME=/var/www/
  if [ ! -d "${WWW_DATA_HOME}" ]; then
  
    printMessage "Creating the www-data home..."
    mkdir -p "${WWW_DATA_HOME}"
  else  
    printMessage "www-data home already exists, skipping"
  fi
  
  printMessage "Setting the ownership for the whole tree..."
  chown www-data:www-data "${WWW_DATA_HOME}" -R

  printMessage "SetGID on the root directory only"
  # Any files created in the directory will have their group set to www-data
  chmod g+s "${WWW_DATA_HOME}"

  printMessage "SetGID on the directories inside..."
  find "${WWW_DATA_HOME}" -type d -exec chmod g+s {} \;

  printMessage "Setting the permissions for the whole tree..."
  chmod u=rwX,g=rX,o= "${WWW_DATA_HOME}" -R
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing PHP-CLI and PHP-FPM..."
if [ $INSTALL_PHP = 1 ]; then
  
 source ${WEBSTACKUP_SCRIPT_DIR}php/install.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing MYSQL..."
if [ $INSTALL_MYSQL = 1 ]; then
  
  source ${WEBSTACKUP_SCRIPT_DIR}mysql/install.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing ELASTICSEARCH..."
if [ $INSTALL_ELASTICSEARCH = 1 ]; then
  
  source ${WEBSTACKUP_SCRIPT_DIR}elasticsearch/install.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing PURE-FTPD..."
if [ $INSTALL_PUREFTPD = 1 ]; then
  
  printMessage "Removing previous version (if any)"
  apt purge --auto-remove pure-ftpd* -y -qq
  source ${WEBSTACKUP_SCRIPT_DIR}pure-ftpd/install.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing COMPOSER..."
if [ $INSTALL_COMPOSER = 1 ]; then

  printMessage "Downloading..."
  COMPOSER_EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  COMPOSER_ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
  
  if [ "$COMPOSER_EXPECTED_SIGNATURE" != "$COMPOSER_ACTUAL_SIGNATURE" ]; then
  
    catastrophicError "Composer signature doesn't match! Abort! Abort!"

Expec. hash: ### ${COMPOSER_EXPECTED_SIGNATURE}
Actual hash: ### ${COMPOSER_ACTUAL_SIGNATURE}"
  fi
  
  printMessage "Installing..."
  php composer-setup.php --filename=composer --install-dir=/usr/local/bin
  php -r "unlink('composer-setup.php');"
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing SYMFONY"
if [ $INSTALL_SYMFONY = 1 ]; then
  
  printMessage "Installing..."
  wget https://get.symfony.com/cli/installer -O - | bash
  mv /root/.symfony/bin/symfony /usr/local/bin/symfony
  
  printMessage "$(symfony -V)"
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing ZZUPDATE..."
if [ $INSTALL_ZZUPDATE = 1 ]; then

  curl -s https://raw.githubusercontent.com/TurboLabIt/zzupdate/master/setup.sh | sudo bash
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing ZZMYSQLDUMP"
if [ $INSTALL_ZZMYSQLDUMP = 1 ]; then

  curl -s https://raw.githubusercontent.com/TurboLabIt/zzmysqldump/master/setup.sh | sudo bash
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing XDEBUG..."
if [ $INSTALL_XDEBUG = 1 ]; then

  printMessage "Installing..."
  apt install php-xdebug -y -qq
  
  printMessage "Activating custom xdebug config..."
  XDEBUG_CONFIG_FILE_FULLPATH="${WEBSTACKUP_INSTALL_DIR}config/php/xdebug.ini"  
  ln -s "$XDEBUG_CONFIG_FILE_FULLPATH" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-xdebug.ini
  ln -s "$XDEBUG_CONFIG_FILE_FULLPATH" /etc/php/${PHP_VER}/cli/conf.d/30-webstackup-xdebug.ini
  
  service php${PHP_VER}-fpm restart

else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing LET'S ENCRYPT..."
if [ $INSTALL_LETSENCRYPT = 1 ]; then
  
  printMessage "Installing..."
  apt install certbot -y -qq
  
  printMessage "$(certbot --version)"

  service cron restart
  
  source "${WEBSTACKUP_SCRIPT_DIR}https/letsencrypt-create-hooks.sh"
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing POSTFIX and OPENDKIM"
if [ $INSTALL_POSTFIX = 1 ]; then

  printMessage "Installing..."
  apt install postfix mailutils opendkim opendkim-tools -y -qq
  
  printMessage "Adding the postfix user to the opendkim group..."
  adduser postfix opendkim
  
  printMessage "Wiring together opendkim and postfix..."
  mkdir /var/spool/postfix/opendkim
  chown opendkim:postfix /var/spool/postfix/opendkim
  
  sed -i -e 's|^UMask|#UMask|g' /etc/opendkim.conf
  sed -i -e 's|^Socket|#Socket|g' /etc/opendkim.conf
  echo "" >>  /etc/opendkim.conf
  echo "" >>  /etc/opendkim.conf
  echo "" >>  /etc/opendkim.conf
  cat "${WEBSTACKUP_INSTALL_DIR}config/opendkim/opendkim_to_be_appended.conf" >> /etc/opendkim.conf
  
  echo "" >>  /etc/postfix/main.cf
  echo "" >>  /etc/postfix/main.cf
  echo "" >>  /etc/postfix/main.cf
  cat "${WEBSTACKUP_INSTALL_DIR}config/opendkim/postfix_to_be_appended.conf" >> /etc/postfix/main.cf
  
  sed -i -e 's|^SOCKET=|#SOCKET=|g' /etc/default/opendkim
  echo "" >> /etc/default/opendkim
  echo "" >> /etc/default/opendkim
  echo "" >> /etc/default/opendkim
  cat "${WEBSTACKUP_INSTALL_DIR}config/opendkim/opendkim-default_to_be_appended.conf" >> /etc/default/opendkim
  
  mkdir -p /etc/opendkim/keys
  
  cp "${WEBSTACKUP_INSTALL_DIR}config/opendkim/TrustedHosts" /etc/opendkim/TrustedHosts
  cp "${WEBSTACKUP_INSTALL_DIR}config/opendkim/KeyTable" /etc/opendkim/KeyTable
  cp "${WEBSTACKUP_INSTALL_DIR}config/opendkim/SigningTable" /etc/opendkim/SigningTable
  
  chown opendkim:opendkim /etc/opendkim/ -R
  chmod ug=rwX,o=rX /etc/opendkim/ -R
  chmod u=rwX,og=X /etc/opendkim/keys -R
  
  service postfix restart
  service opendkim restart
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing NTP..."
if [ $INSTALL_NTP = 1 ]; then

  printMessage "Installing..."
  apt install ntp -y -qq
  
  service ntp restart
  systemctl --no-pager status ntp
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing ZZALIAS..."
if [ $INSTALL_ZZALIAS = 1 ]; then

  curl -s https://raw.githubusercontent.com/TurboLabIt/zzalias/master/setup.sh | sudo bash
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Firewalling..."
if [ $INSTALL_FIREWALL = 1 ]; then

   curl -s https://raw.githubusercontent.com/TurboLabIt/zzfirewall/master/setup.sh | sudo bash
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Creating users..."
if [ ! -z $INSTALL_USERS_TEMPLATE_PATH ]; then

  bash "${WEBSTACKUP_SCRIPT_DIR}account/create_and_copy_template.sh" "$INSTALL_USERS_TEMPLATE_PATH"
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Disable SSH password login..."
if [ $INSTALL_SSH_DISABLE_PASSWORD_LOGIN = 1 ]; then

  ln -s "${WEBSTACKUP_INSTALL_DIR}config/ssh/disable-password-login.conf" /etc/ssh/sshd_config.d/
  service sshd restart
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing CHROME..."
if [ $INSTALL_CHROME = 1 ]; then
  
  source ${WEBSTACKUP_SCRIPT_DIR}chrome/install.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing cron..."
cp "${WEBSTACKUP_INSTALL_DIR}config/cron/webstackup" /etc/cron.d/


printTitle "Running cloning wizard..."
if [ $INSTALL_GIT_CLONE_WEBAPP = 1 ]; then

  bash ${WEBSTACKUP_SCRIPT_DIR}filesystem/git-clone-a-webapp.sh
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "Installing and running benchmark..."
if [ $INSTALL_BENCHMARK = 1 ]; then

  apt install sysbench -y -qq
  sysbench cpu --threads=1 run
  
  printMessage "Cfr i7-9750H: 1415 (events per second) | 14162 (total number of events)"
  
else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTitle "REBOOTING..."
if [ "$REBOOT" = "1" ] && [ "$INSTALL_ZZUPDATE" = 1 ]; then

  fxCountdown
  zzupdate

elif [ "$REBOOT" = "1" ]; then

  fxCountdown
  shutdown -r -t 5

else
  
  printLightWarning "Skipped (disabled in config)"
fi


printTheEnd
