#!/usr/bin/env bash
### AUTOMATIC PHP INSTALL BY WEBSTACK.UP
# https://github.com/TurboLabIt/webstackup/tree/master/script/php/install.sh

source "/usr/local/turbolab.it/webstackup/script/base.sh"

fxHeader "⚙️ PHP INSTALL"
rootCheck

if [ -z "${PHP_VER}" ]; then
  fxCatastrophicError "PHP_VER is undefined! Cannot determine which version of PHP to install"
fi

fxTitle "Setting up ondrej/php"
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
apt update -qq

fxTitle "Installing..."
apt install php${PHP_VER}-fpm php${PHP_VER}-cli php${PHP_VER}-common php${PHP_VER}-mbstring php${PHP_VER}-gd php${PHP_VER}-intl php${PHP_VER}-xml php${PHP_VER}-mysql php${PHP_VER}-zip php${PHP_VER}-curl -y -qq

fxTitle "Storing the version..."
echo "set \$PHP_VER ${PHP_VER};"  > "${WEBSTACKUP_AUTOGENERATED_DIR}nginx-php_ver.conf"
echo "PHP_VER=${PHP_VER}" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
echo "PHP_FPM=php${PHP_VER}-fpm" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
echo "PHP_CLI=/usr/bin/php${PHP_VER}" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
  
fxTitle "Activating custom php.ini..."  
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/php-custom.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-custom.ini
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/php-custom.ini" /etc/php/${PHP_VER}/cli/conf.d/30-webstackup-custom.ini

fxTitle "Disabling execution function from FPM..."  
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/no-exec.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-no-exec.ini
  
fxTitle "Set timezone to Italy..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/timezone-italy.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-timezone-italy.ini
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/timezone-italy.ini" /etc/php/${PHP_VER}/cli/conf.d/30-webstackup-timezone-italy.ini

fxTitle "Removing all limits from CLI..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/unlimited.ini" /etc/php/${PHP_VER}/cli/conf.d/35-webstackup-unlimited.ini
  
fxTitle "Disable cgi.fix_pathinfo from FPM..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/no-cgi.fix_pathinfo.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-no-cgi.fix_pathinfo.ini

fxTitle "Enable OPcache..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/opcache.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-opcache.ini

fxTitle "Activating custom php-fpm pool settings..."
if [ "$INSTALLED_RAM" -gt "6000" ]; then
  
  echo "RAM: ${INSTALLED_RAM}: using fpm-pool-32GB.conf"
  ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/fpm-pool-32GB.conf" /etc/php/${PHP_VER}/fpm/pool.d/webstackup-fpm-pool-32GB.conf
    
else
  
  echo "RAM: ${INSTALLED_RAM}: this is a small server! Using fpm-pool-1GB.conf"
  ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/fpm-pool-1GB.conf" /etc/php/${PHP_VER}/fpm/pool.d/zz-webstackup-fpm-pool-1GB.conf
fi
  
fxTitle "Assigning the nginx user to www-data group..."
usermod -a -G www-data nginx
service nginx restart
  
fxTitle "Create the socket directory..."
mkdir -p /run/php/
  
service php${PHP_VER}-fpm restart
systemctl --no-pager status php${PHP_VER}-fpm
  
fxTitle "Linking the PHP-FPM socket as php-fpm.sock..."
if [ ! -e "/run/php/php-fpm.sock" ]; then
  ln -s /run/php/php${PHP_VER}-fpm.sock /run/php/php-fpm.sock
else
  echo "Link already exists"
  ls -l "/run/php/php-fpm.sock"
fi

fxEndFooter
