#!/usr/bin/env bash
### AUTOMATIC PHP INSTALL BY WEBSTACK.UP

if ! [ $(id -u) = 0 ]; then

    echo "This script must run as ROOT"
    exit
fi

printMessage "Removing previous version (if any)"
apt purge --auto-remove php* -y -qq
  
printMessage "Setting up ondrej/php"
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y
apt update -qq

printMessage "Installing..."
apt install php${PHP_VER}-fpm php${PHP_VER}-cli php${PHP_VER}-common php${PHP_VER}-mbstring php${PHP_VER}-gd php${PHP_VER}-intl php${PHP_VER}-xml php${PHP_VER}-mysql php${PHP_VER}-zip php${PHP_VER}-curl -y -qq
  
echo "PHP_VER=${PHP_VER}" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
echo "PHP_FPM=php${PHP_VER}-fpm" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
echo "PHP_CLI=/usr/bin/php${PHP_VER}" >> "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
  
printMessage "Activating custom php.ini..."  
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/php-custom.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-custom.ini
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/php-custom.ini" /etc/php/${PHP_VER}/cli/conf.d/30-webstackup-custom.ini
  
printMessage "Set timezone to Italy..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/timezone-italy.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-timezone-italy.ini
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/timezone-italy.ini" /etc/php/${PHP_VER}/cli/conf.d/30-webstackup-timezone-italy.ini
  
printMessage "Disable cgi.fix_pathinfo..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/no-cgi.fix_pathinfo.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-no-cgi.fix_pathinfo.ini

printMessage "Enable OPcache..."
ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/opcache.ini" /etc/php/${PHP_VER}/fpm/conf.d/30-webstackup-opcache.ini

printMessage "Activating custom php-fpm pool settings..."
if [ "$INSTALLED_RAM" -gt "6000" ]; then
  
  echo "RAM: ${INSTALLED_RAM}: using fpm-pool-32GB.conf"
  ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/fpm-pool-32GB.conf" /etc/php/${PHP_VER}/fpm/pool.d/webstackup-fpm-pool-32GB.conf
    
else
  
  echo "RAM: ${INSTALLED_RAM}: this is a small server! Using fpm-pool-1GB.conf"
  ln -s  "${WEBSTACKUP_INSTALL_DIR}config/php/fpm-pool-1GB.conf" /etc/php/${PHP_VER}/fpm/pool.d/zz-webstackup-fpm-pool-1GB.conf
fi
  
printMessage "Assigning the nginx user to www-data group..."
usermod -a -G www-data nginx
service nginx restart
  
printMessage "Create the socket directory..."
mkdir -p /run/php/
  
service php${PHP_VER}-fpm restart
systemctl --no-pager status php${PHP_VER}-fpm
  
printMessage "Aliasing the PHP-FPM socket as php-fpm.sock..."
ln -s /run/php/php${PHP_VER}-fpm.sock /run/php/php-fpm.sock
