#!/usr/bin/env bash
### SET PHP VARIABLES SUCH AS PHP_VER AND PHP_CLI BY WEBSTACK.UP
#
# PHP_VER = '8.2'
# PHP_CLI = 'XDEBUG_MODE=off /bin/php8.2'
# PHP_FPM = 'php8.2-fpm'

# COMPOSER_EXE    = '${PHP_CLI} /usr/local/bin/composer --no-interaction'
# SYMFONY_EXE     = '${PHP_CLI} /usr/local/bin/symfony'
# N98_MAGERUN_EXE = '${PHP_CLI} /usr/local/bin/n98-magerun2'
# WP_CLI_EXE      = '${PHP_CLI} /usr/local/bin/wp-cli'


fxTitle "🧰 Setting PHP version..."

if [ -r "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh" ]; then
  source "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
  fxMessage "🌎 PHP version set to ${PHP_VER} from ${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
fi


if [ ! -z "${PROJECT_DIR}" ] && [ -f "${PROJECT_DIR}.php-version" ]; then
  PHP_VER="$(head -n 1 "${PROJECT_DIR}.php-version")"
  fxMessage "📁 PHP version set to ${PHP_VER} from ${PROJECT_DIR}.php-version"
fi


if [ -z "${PHP_VER}" ]; then

  fxWarning "No PHP_VER has been set"

elif

  PHP_CLI="XDEBUG_MODE=off /bin/php${PHP_VER}"
  PHP_FPM="php${PHP_VER}-fpm"
  
  COMPOSER_EXE="${PHP_CLI} /usr/local/bin/composer --no-interaction"
  SYMFONY_EXE="${PHP_CLI} /usr/local/bin/symfony"
  MAGE_CLI_EXE="${PROJECT_DIR}shop && ${PHP_CLI} bin/magento"
  N98_MAGERUN_EXE="${PHP_CLI} /usr/local/bin/n98-magerun2"
  WP_CLI_EXE="${PHP_CLI} /usr/local/bin/wp-cli"
  
fi
