#!/usr/bin/env bash
### SET PHP VARIABLES SUCH AS PHP_VER AND PHP_CLI BY WEBSTACK.UP
#
# PHP_VER = '8.2'
# PHP_CLI = '/bin/php8.2'
# PHP_FPM = 'php8.2-fpm'

PHP_KNOWN_VERSIONS=(5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1 8.2 8.3 8.4)

if [ -r "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh" ]; then
  source "${WEBSTACKUP_AUTOGENERATED_DIR}variables.sh"
  PHP_VER_FROM_GLOBAL=${PHP_VER}
fi

if [ ! -z "${PROJECT_DIR}" ] && [ -f "${PROJECT_DIR}.php-version" ]; then
  PHP_VER="$(head -n 1 "${PROJECT_DIR}.php-version")"
  PHP_VER_FROM_PROJECT=${PHP_VER}
fi

PHP_CLI="/bin/php${PHP_VER}"
PHP_FPM="php${PHP_VER}-fpm"

showPHPVer()
{
  fxTitle "PHP version..."
  if [ -z "${PHP_VER}" ]; then
    fxWarning "No PHP_VER has been set"
  else
    echo "PHP_VER from global:   ${PHP_VER_FROM_GLOBAL}"
    echo "PHP_VER from project:  ${PHP_VER_FROM_PROJECT}"
    fxMessage "PHP_VER set to:        ${PHP_VER}"
  fi
}
