#!/usr/bin/env bash

## bash-fx
if [ -f "/usr/local/turbolab.it/bash-fx/bash-fx.sh" ]; then
  source "/usr/local/turbolab.it/bash-fx/bash-fx.sh"
else
  if [ -z $(command -v curl) ]; then sudo apt update && sudo apt install curl -y; fi
  source <(curl -s https://raw.githubusercontent.com/TurboLabIt/bash-fx/main/bash-fx.sh)
fi
## bash-fx is ready


fxHeader "🩹 HTTPS SELF-SIGNED CERTIFICATE GENERATOR"
rootCheck

WSU_CERT_PATH_DEFAULT=/usr/local/turbolab.it/webstackup/autogenerated/


if [ ! -z "${1}" ]; then
  WSU_MAP_DOMAIN_DEFAULT=${1}
  WSU_CERT_WILDCARD=1
  WSU_CERT_PATH=${WSU_CERT_PATH_DEFAULT}
fi


fxTitle "📛 Enter the base domain"
fxInfo "For example: \"turbolab.it\" or \"next.turbolab.it\""
while [ -z "$WSU_MAP_DOMAIN_DEFAULT" ]; do

  echo "🤖 Provide the domain"
  read -p ">> " WSU_MAP_DOMAIN_DEFAULT  < /dev/tty

done

fxOK "OK, working on ##$WSU_MAP_DOMAIN_DEFAULT##"


fxTitle "🃏 Wildcard?"
while [ -z "$WSU_CERT_WILDCARD" ]; do

  echo "🤖 *.${WSU_MAP_DOMAIN_DEFAULT}? Hit Enter for 'yes'"
  read -p ">> " -n 1 -r  < /dev/tty
  if [[ ! "$REPLY" =~ ^[Nn0]$ ]]; then
    WSU_CERT_WILDCARD=1
  else
    WSU_CERT_WILDCARD=0
  fi

  echo ""

done


if [ "${WSU_CERT_WILDCARD}" == 0 ]; then
  WSU_CERT_COMPLETE_DOMAIN=${WSU_MAP_DOMAIN_DEFAULT}
else
  WSU_CERT_COMPLETE_DOMAIN="*.${WSU_MAP_DOMAIN_DEFAULT}"
fi

fxOK "OK, the cert will be valid for ##${WSU_CERT_COMPLETE_DOMAIN}##"


fxTitle "📂 Enter the path to save the cert file"
while [ -z "$WSU_CERT_PATH" ]; do

  echo "🤖 Provide the path (use TAB!) or hit Enter for ##${WSU_CERT_PATH_DEFAULT}##"
  read -ep ">> " WSU_CERT_PATH  < /dev/tty
  if [ -z "$WSU_CERT_PATH" ]; then
    WSU_CERT_PATH=$WSU_CERT_PATH_DEFAULT
  fi

done

WSU_CERT_PATH=${WSU_CERT_PATH%*/}/
WSU_CERT_FILE_FULLPATH=${WSU_CERT_PATH}https-${WSU_MAP_DOMAIN_DEFAULT}.crt
fxOK "Aye, aye! The cert will be saved in ##$WSU_CERT_FILE_FULLPATH##"


#fxTitle "Preparing the configuration template..."
#cp "/usr/local/turbolab.it/webstackup/config/https/self-sign-template.conf" "${WSU_CERT_PATH}self-signed.conf"
#sed -i "s/localhost/${WSU_CERT_COMPLETE_DOMAIN}/g" "${WSU_CERT_PATH}self-signed.conf"
#cat "${WSU_CERT_PATH}self-signed.conf"


fxTitle "Checking the private key..."
SELFSIGN_KEY=/usr/local/turbolab.it/webstackup/autogenerated/openssl-private-key.pem
if [ ! -f "${SELFSIGN_KEY}" ]; then

  fxInfo "Private key not found. Generating..."
  openssl genrsa -out "${SELFSIGN_KEY}"
fi

fxOK "Using private key ##${SELFSIGN_KEY}##"


fxTitle "Generating the certificate..."
openssl req -x509 -key "${SELFSIGN_KEY}" \
  -days 36500 -sha256 -new \
  -out "${WSU_CERT_FILE_FULLPATH}" \
  -subj "/CN=${WSU_CERT_COMPLETE_DOMAIN}/O=webstackup/OU=self-sign-generate.sh" \
  -addext "subjectAltName=DNS:${WSU_CERT_COMPLETE_DOMAIN},DNS:${WSU_MAP_DOMAIN_DEFAULT}" \
  -addext "keyUsage=digitalSignature" \
  -addext "extendedKeyUsage=serverAuth" \
  -addext "basicConstraints=CA:FALSE"


fxTitle "Self-signed certificate ready!"
fxMessage "ssl_certificate ${WSU_CERT_FILE_FULLPATH};"
fxMessage "ssl_certificate_key ${SELFSIGN_KEY};"


fxEndFooter
