#!/bin/bash

## Script name
SCRIPT_NAME=self-sign-generate

## Title and graphics
FRAME="O===========================================================O"
echo "$FRAME"
echo " Generate self-signed, bogus certificate WEBSTACK.UP - $(date)"
echo "$FRAME"

## Enviroment variables
TIME_START="$(date +%s)"
DOWEEK="$(date +'%u')"
HOSTNAME="$(hostname)"

SSL_DIR=${AUTOGENERATED_DIR}


## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898470
#touch "$HOME/.rnd"


openssl req -x509 -out ${SSL_DIR}ssl_certificate.crt -keyout ${SSL_DIR}ssl_certificate_key.key \
	-days 3650 \
	-newkey rsa:2048 -nodes -sha256 \
	-subj '/CN=localhost' -extensions EXT -config <( \
		printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")

##
printMessage "Bogus HTTPS certificate ready"
printMessage "$(ls -la "${AUTOGENERATED_DIR}" | grep ssl_certificate)"


## =========== The End ===========
printTitle "Time took"
echo "$((($(date +%s)-$TIME_START)/60)) min."

printTitle "The End"
echo $(date)
echo "$FRAME"
