<?php
/**
 * Banner
 * ======
 */
echo "⚙️ Adding banner..." . PHP_EOL;
$txtWhitelist    = '## ☠️ WARNING! This file is AUTOGENERATED by Webstackup! Do not edit!';
$txtWhitelist   .= PHP_EOL . '## See: https://github.com/TurboLabIt/webstackup/';

/**
 * Allow connections from a static whitelist...
 * ============================================
 */
const WSA_WHITELIST_URL = 'https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-whitelist.txt';
echo "⚙️ Adding from static whitelist " . WSA_WHITELIST_URL . "..." . PHP_EOL;
$txtWhitelist   .= PHP_EOL . PHP_EOL . file_get_contents(WSA_WHITELIST_URL);

/**
 * Allow connections from Google...
 * ================================
 */
const GOOGLE_WHITELIST_URL = 'https://www.gstatic.com/ipranges/goog.json';
echo "⚙️ Adding from Google " . GOOGLE_WHITELIST_URL . "..." . PHP_EOL;
$txtWhitelist   .= PHP_EOL . PHP_EOL . '## 🔎 Allow from Google - ' . GOOGLE_WHITELIST_URL;
$txtGoogle = file_get_contents(GOOGLE_WHITELIST_URL);
$arrGoogle = json_decode($txtGoogle);

foreach($arrGoogle->prefixes as $oneItem) {

    if( empty($oneItem->ipv4Prefix) ) {
        continue;
    }

    $txtWhitelist .= PHP_EOL . $oneItem->ipv4Prefix;
}

/**
 * Writing the file...
 * ===================
 */
$txtWhitelist .= PHP_EOL . PHP_EOL;
const WHITELIST_OUT_PATH = '/usr/local/turbolab.it/webstackup/config/firewall/autogen_whitelist.txt';
echo "⚙️ Writing the file to " . WHITELIST_OUT_PATH . "..." . PHP_EOL;
file_put_contents(WHITELIST_OUT_PATH, $txtWhitelist);

echo PHP_EOL . basename(__FILE__, '.php') . " is DONE" . PHP_EOL;
