#!/bin/bash
echo ""

source "/usr/local/turbolab.it/webstackup/script/base.sh"
printHeader "🛡️ Generate black|white list"
rootCheck

printMessage "Generate whitelist..."
php ${WEBSTACKUP_SCRIPT_DIR}firewall/generate-whitelist.php


# printMessage "Generate blacklist..."
# php ${WEBSTACKUP_SCRIPT_DIR}firewall/generate-blacklist.php

printMessage "Git commit..."
git -C ${WEBSTACKUP_INSTALL_DIR} add ${WEBSTACKUP_CONFIG_DIR}firewall/autogen_whitelist.txt
git -C ${WEBSTACKUP_INSTALL_DIR} commit -m"🧱 autogenerated firewall lists update"

printMessage "Git pull and push..."
git -C ${WEBSTACKUP_INSTALL_DIR} pull --no-edit
git -C ${WEBSTACKUP_INSTALL_DIR} push
