<?php
/**
 * Banner
 * ======
 */
echo "⚙️ Adding banner..." . PHP_EOL;
$txtBlacklist    = '## ☠️ WARNING! This file is AUTOGENERATED by Webstackup! Do not edit!';
$txtBlacklist   .= PHP_EOL . '## See: https://github.com/TurboLabIt/webstackup/';


/**
 * Deny connections from some ready-to-use blacklists
 * ============================================
 */
$arrLists = [
    'https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist.txt',
    'https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level1.netset'
];

foreach($arrLists as $oneList) {

    echo "⚙️ Adding from  " . $oneList . "..." . PHP_EOL;
    $txtBlacklist   .= PHP_EOL . PHP_EOL . file_get_contents($oneList);
}


/**
 * Deny connections from ipsum
 * ===========================
 */
const IPSUM_BLACKLIST_URL = 'https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt';
echo "⚙️ Adding from " . IPSUM_BLACKLIST_URL . "..." . PHP_EOL;
$txtIpsum   = file_get_contents(IPSUM_BLACKLIST_URL);
$arrIpsum   = explode(PHP_EOL, $txtIpsum);
foreach($arrIpsum as $lineIpsum) {

    if( empty(trim($lineIpsum)) || $lineIpsum[0] == '#' ) {
        $txtBlacklist   .= PHP_EOL . $lineIpsum;
        continue;
    }

    $newLine = mb_substr($lineIpsum, 0, mb_strpos($lineIpsum, "\t"));
    $txtBlacklist .= PHP_EOL . $newLine;
}


/**
 * Writing the file...
 * ===================
 */
$txtBlacklist .= PHP_EOL . PHP_EOL;
const BLACKLIST_OUT_PATH = '/usr/local/turbolab.it/webstackup/config/firewall/autogen_blacklist.txt';
echo "⚙️ Writing the file to " . BLACKLIST_OUT_PATH . "..." . PHP_EOL;
file_put_contents(BLACKLIST_OUT_PATH, $txtBlacklist);

echo PHP_EOL . basename(__FILE__, '.php') . " is DONE" . PHP_EOL;
