#!/bin/bash
echo ""

source "/usr/local/turbolab.it/webstackup/script/base.sh"
printHeader "🛡️ persona-non-grata"
rootCheck


printTitle "📦 Checking packages...."
if [ -z "$(command -v curl)" ] || [ -z "$(command -v iptables)" ] || [ -z "$(command -v ipset)" ]; then

  printMessage "Installing packages..."
  apt update
  apt install iptables ipset curl -y
  
else

  printMessage "✔ iptables and ipset are already installed"
fi


printTitle "🧹 Clear the log file..."
mkdir -p "${WEBSTACKUP_AUTOGENERATED_DIR}"
PNG_IP_LOG_FILE=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata.log
date +"%Y-%m-%d %T" > "${PNG_IP_LOG_FILE}"


printTitle "⏬ Downloading IP white list..."
IP_WHITELIST_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}firewall_whitelist.txt
curl -Lo "${IP_WHITELIST_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/autogen_whitelist.txt
echo "" >> $IP_WHITELIST_FULLPATH


printTitle "⏬ Downloading IP block list..."
IP_BLACKLIST_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata.txt
curl -Lo "${IP_BLACKLIST_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist.txt
echo "" >> $IP_BLACKLIST_FULLPATH


printTitle "⏬ Appending http://iplists.firehol.org/ ..."
echo "## http://iplists.firehol.org/" >> $IP_BLACKLIST_FULLPATH
curl https://raw.githubusercontent.com/ktsaou/blocklist-ipsets/master/firehol_level1.netset >> $IP_BLACKLIST_FULLPATH
echo "" >> $IP_BLACKLIST_FULLPATH


printTitle "⏬ Appending https://github.com/stamparm/ipsum ..."
echo "## https://github.com/stamparm/ipsum" >> $IP_BLACKLIST_FULLPATH
curl --compressed https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt 2>/dev/null | grep -v "#" | grep -v -E "\s[1-2]$" | cut -f 1 >> $IP_BLACKLIST_FULLPATH


printTitle "⏬ Downloading Arab IP list..."
IP_BLACKLIST_ARAB_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata-blacklist-geo-arab.txt
curl -Lo "${IP_BLACKLIST_ARAB_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist-geo-arab.txt


printTitle "⏬ Downloading China IP list..."
IP_BLACKLIST_CHINA_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata-blacklist-geo-china.txt
curl -Lo "${IP_BLACKLIST_CHINA_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist-geo-china.txt


printTitle "⏬ Downloading India IP list..."
IP_BLACKLIST_INDIA_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata-blacklist-geo-india.txt
curl -Lo "${IP_BLACKLIST_INDIA_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist-geo-india.txt


printTitle "⏬ Downloading Korea IP list..."
IP_BLACKLIST_KOREA_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata-blacklist-geo-korea.txt
curl -Lo "${IP_BLACKLIST_KOREA_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist-geo-korea.txt


printTitle "⏬ Downloading Russia IP list..."
IP_BLACKLIST_RUSSIA_FULLPATH=${WEBSTACKUP_AUTOGENERATED_DIR}persona-non-grata-blacklist-geo-russia.txt
curl -Lo "${IP_BLACKLIST_RUSSIA_FULLPATH}" https://raw.githubusercontent.com/TurboLabIt/webstackup/master/config/firewall/persona-non-grata-blacklist-geo-russia.txt


printTitle "Checking ufw...."
if [ -z "$(command -v ufw)" ]; then

  printMessage "✔ ufw is not installed"
  UFW_INACTIVE=1
  
else

  ufw status | grep -qw active
  UFW_INACTIVE=$?
fi
  
if [ $UFW_INACTIVE != 1 ]; then

  printMessage "Disabling ufw..."
  ufw --force reset
  ufw disable
  
else 
  
  printMessage "✔ ufw is not enabled"
fi


printTitle "🧹 Try to uninstall iptables-persistent..."
apt purge iptables-persistent -y


printTitle "🧹 Reset iptables..."
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

ip6tables -P INPUT ACCEPT
ip6tables -P FORWARD ACCEPT
ip6tables -P OUTPUT ACCEPT
ip6tables -t nat -F
ip6tables -t mangle -F
ip6tables -F
ip6tables -X


printTitle "🧹 Cleaning up previous persona-non-grata ipset set..."
ipset destroy PersonaNonGrata


printTitle "☀ Creating new sets..."
function pngCreateSet ()
{
  printTitle "🧱 Building ipset $1 from file..."
  ipset destroy $1
  ipset create $1 nethash
  while read -r line || [[ -n "$line" ]]; do
    local FIRSTCHAR="${line:0:1}"
    if [ "$FIRSTCHAR" != "#" ] && [ "$FIRSTCHAR" != "" ]; then
      echo "Add: $line" >> "${PNG_IP_LOG_FILE}"
      ipset add $1 $line
    fi  
  done < "$2"
}

pngCreateSet PersonaNG_Whitelist "$IP_WHITELIST_FULLPATH"
pngCreateSet PersonaNG_Blacklist "$IP_BLACKLIST_FULLPATH"
pngCreateSet PersonaNG_GeoArab "$IP_BLACKLIST_ARAB_FULLPATH"
pngCreateSet PersonaNG_GeoChina "$IP_BLACKLIST_CHINA_FULLPATH"
pngCreateSet PersonaNG_GeoIndia "$IP_BLACKLIST_INDIA_FULLPATH"
pngCreateSet PersonaNG_GeoKorea "$IP_BLACKLIST_KOREA_FULLPATH"
pngCreateSet PersonaNG_GeoRussia "$IP_BLACKLIST_RUSSIA_FULLPATH"


printTitle "🚪 Creating iptables rules..."

printMessage "🏡 Allow from localhost..."
iptables -A INPUT -i lo -j ACCEPT

printMessage "🎅 Drop XMAS packets..."
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP

printMessage "💩 Drop null packets..."
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

printMessage "📤 Allow ESTABLISHED,RELATED..."
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

printMessage "🏡 Allow connections from LAN..."
iptables -A INPUT -s 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 -j ACCEPT

printMessage "👐 Enable ipset whitelist..."
iptables -A INPUT -p tcp -m multiport --dport 80,443 -m set --match-set PersonaNG_Whitelist src -j ACCEPT

function pngAddDropRule ()
{
  printMessage "🛑 Enable ipset ${1}..."
  iptables -A INPUT -m set --match-set ${1} src -j DROP
}

pngAddDropRule PersonaNG_Blacklist
pngAddDropRule PersonaNG_GeoArab
pngAddDropRule PersonaNG_GeoChina
pngAddDropRule PersonaNG_GeoIndia
pngAddDropRule PersonaNG_GeoKorea
pngAddDropRule PersonaNG_GeoRussia

printMessage "🐧 Allow SSH..."
iptables -A INPUT -p tcp -m multiport --dport 22,222 -j ACCEPT

printMessage "📁 Allow FTP/FTPS"
iptables -A INPUT -p tcp -m multiport --dport 20,21,990,2121:2221 -j ACCEPT

printMessage "💌 Allow SMTP..."
iptables -A INPUT -p tcp --dport 25 -j ACCEPT

printMessage "🌎 Allow HTTP(s)..."
iptables -A INPUT -p tcp -m multiport --dport 80,443 -j ACCEPT

printMessage "📉 Allow monitor..."
iptables -A INPUT -p tcp -m multiport --dport 5666 -j ACCEPT

printMessage "🛑 Drop everything else..."
iptables -A INPUT -j DROP


printTitle "🍃 Looking for pure-ftpd..."
if [ -d /etc/pure-ftpd/conf/ ]; then
  
  printMessage "pure-ftpd found! Updating PassivePortRange..."
  rm -f /etc/pure-ftpd/conf/PassivePortRange
  ln -s "${WEBSTACKUP_CONFIG_DIR}pure-ftpd/PassivePortRange" "/etc/pure-ftpd/conf/PassivePortRange"
  ls -la /etc/pure-ftpd/conf/
  cat /etc/pure-ftpd/conf/PassivePortRange
  service pure-ftpd restart
  
else 
  printMessage "pure-ftpd not found. No PassivePortRange updated."
fi

function pngPrintIpSet ()
{
  printTitle "ipset $1"
  ipset list $1 | head -n 7
  echo "...."
}

pngPrintIpSet PersonaNG_Blacklist
pngPrintIpSet PersonaNG_GeoArab
pngPrintIpSet PersonaNG_GeoChina
pngPrintIpSet PersonaNG_GeoIndia
pngPrintIpSet PersonaNG_GeoKorea
pngPrintIpSet PersonaNG_GeoRussia

printTitle "✅ persona-non-grata is done"
printMessage "iptables"
iptables -nvL

printTitle "Need the log?"
printMessage "nano ${PNG_IP_LOG_FILE}"
